### ISSUE TITLE
Do you have an updated version for Swift 4.2+?

### ISSUE THREAD

**Issue by shyamalschandra** [rizwankce/Camera#7]
Do you have an updated version for Swift 4.2+?

**Comment by rizwankce** [comment]
Haven't ported it to 4.2+. But should be easy. I'll try to update the whole project 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shyamalschandra** [comment]
Okay, great!  Please let me know when it is done.

**Comment by rizwankce** [comment]
I totally forgot that I already updated the project to swift 4.2.  You can check #6 

Current master branch is working fine with latest Xcode and migrated to 4.2

**Comment by shyamalschandra** [comment]
Thank you!
